services:
  - type: web
    name: fastapi-movie-api
    runtime: python
    buildCommand: ""
    startCommand: gunicorn movies.api.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: PORT
        value: 10000
