services:
  - type: web
    name: fastapi-movie-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn movies.api.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
